## Ridge Regression Gradient Descent from Scratch

### Model Equation:
### $$  y = b_0 + \sum_{i=1}^{n} b_i X_i $$

### Loss Function:
### $$ L = (Y - Y{\text{pred}})^T(Y - Y{\text{pred}}) + \lambda W^TW   $$

### Gradient Descent Updation Rule:
### $$ \beta_{\text{new}} = \beta_{\text{old}} - \eta \cdot (slope) $$

### Slope Equation:
### $$ \text{slope} = X^TXW - X^TY + \lambda W $$

In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score

from sklearn.model_selection import train_test_split

from sklearn.linear_model import  SGDRegressor , Ridge

In [43]:
class gradient_ridge:

    def __init__(self , alpha ,  learning_rate , epochs):

        self.alpha = alpha
        self.lr = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None

    def fit(self , X_train , Y_train):
        X = X_train.values if isinstance(X_train , pd.DataFrame) else X_train
        Y = Y_train.values if isinstance(Y_train , pd.DataFrame) else Y_train

        X = np.insert(X , 0 , 1, axis = 1)

        self.coef_ = np.ones((X.shape[1],1))
        self.coef_[0] = 0

        # print(self.coef_.shape)

        for _ in range(self.epochs):


            slope = np.dot(X.T, np.dot(X, self.coef_)) - np.dot(X.T, Y.reshape(-1, 1)) + (self.alpha * self.coef_)
            self.coef_ = self.coef_ - (self.lr * slope)
        
        self.intercept_ = self.coef_[0]
        self.coef_ = self.coef_[1:]

    def predict(self , X_test):
        X = X_test.values if isinstance(X_test , pd.DataFrame) else X_test

        return np.dot(X , self.coef_) + self.intercept_
        

In [44]:
X , Y = load_diabetes(return_X_y = True)

X.shape , Y.shape

((442, 10), (442,))

In [45]:
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size = 0.2 , random_state = 4)

X_train.shape , X_test.shape , Y_train.shape , Y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [46]:
obj = gradient_ridge(alpha = 0.001  , learning_rate = 0.005 , epochs = 500)

obj.fit(X_train , Y_train)

obj.intercept_ , obj.coef_

(array([150.86975317]),
 array([[  46.65050914],
        [-221.3750037 ],
        [ 452.12080647],
        [ 325.54248128],
        [ -29.09464178],
        [ -96.47517735],
        [-190.90017011],
        [ 146.32900372],
        [ 400.80267299],
        [  95.09048094]]))

In [47]:
y_pred = obj.predict(X_test)

r2 = r2_score(Y_test , y_pred)
adj_r2 = 1 - ( ( ( 1- r2) * (X_test.shape[0]) ) / ( X_test.shape[0] - 1 - X_test.shape[1] ) )

print(f' R2 Socre : {r2}')
print(f' Adjusted R2 Score : {adj_r2}')

 R2 Socre : 0.4738018280260915
 Adjusted R2 Score : 0.3995943935169505


## Using SKLearn SGDRegressor

In [48]:
sgd_reg = SGDRegressor(penalty='l2' , max_iter=500 , eta0 = 0.1 , learning_rate = 'constant' , alpha = 0.001)

sgd_reg.fit(X_train , Y_train)

sgd_reg.intercept_ , sgd_reg.coef_

(array([166.83510106]),
 array([  48.29388371, -141.55193044,  355.78064078,  265.05237615,
          -0.64997879,  -53.47451528, -163.50849345,  137.10760699,
         319.82592264,  104.34235018]))

In [49]:
y_pred_sk = sgd_reg.predict(X_test)

r2 = r2_score(Y_test , y_pred_sk)
adj_r2 = 1 - ( ( ( 1- r2) * (X_test.shape[0]) ) / ( X_test.shape[0] - 1 - X_test.shape[1] ) )

print(f' R2 Socre : {r2}')
print(f' Adjusted R2 Score : {adj_r2}')

 R2 Socre : 0.4364877293322569
 Adjusted R2 Score : 0.3570180501355239


## Using SKLearn Ridge 

In [50]:
reg = Ridge(alpha = 0.001 , max_iter = 500 , solver = 'sparse_cg')

reg.fit(X_train , Y_train)

reg.intercept_ , reg.coef_

(151.1019852106396,
 array([  34.52193585, -290.84083165,  482.40182815,  368.06788002,
        -852.44871579,  501.59161927,  180.11114394,  270.76336042,
         759.73536282,   37.49136954]))

In [51]:
y_pred_sk = reg.predict(X_test)

r2 = r2_score(Y_test , y_pred_sk)
adj_r2 = 1 - ( ( ( 1- r2) * (X_test.shape[0]) ) / ( X_test.shape[0] - 1 - X_test.shape[1] ) )

print(f' R2 Socre : {r2}')
print(f' Adjusted R2 Score : {adj_r2}')

 R2 Socre : 0.46250101621477147
 Adjusted R2 Score : 0.386699877475829
